site_name: CubeXpress
site_url: https://andesdatacube.github.io/cubexpress/
site_author: IPL-UV
site_description: A Python package for efficient processing of cubic earth observation (EO) data.

repo_url: https://github.com/andesdatacube/cubexpress/
repo_name: cubexpress
use_directory_urls: false

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: '#d49f0c'
      accent: '#d49f0c'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo_cubexpress.png
  favicon: logo_cubexpress.png
  features:
    - navigation.instant
    - navigation.top
    - navigation.indexes

extra_css:
  - style.css

nav:
  - Home: index.md
  - API Reference: api.md
  - How it works: process.md
  - GEE methods:
    - Overview: comparation.md
    - getPixels: Comparation/eedatagetPixels.md
    - computePixels: Comparation/eedatacomputePixels.md
    - Conclusion: Comparation/conclusion.md
  - Contributing: CONTRIBUTING.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist