docs_dir: .

# Project information
site_name: CubeXpress
site_url: https://juliocontrerash.github.io/cubexpress/
site_author: IPL-UV
site_description: A Python package for efficient processing of cubic earth observation (EO) data.


# Repository
repo_url: https://github.com/juliocontrerash/cubexpress/
repo_name: cubexpress
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: '#d49f0c'
      accent: '#d49f0c'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: ./docs/logo_cubexpress.png
  favicon: ./docs/logo_cubexpress.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide   


extra_css:
  - ./docs/style.css

# Page tree
nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md
  - Functions: 
    - ./docs/functions.md
  - Processes: 
    - ./docs/process.md
  - eeFunctions:
    - ./docs/comparation.md
    - Get: ./docs/Comparation/eedatagetPixels.md
    - Compute: ./docs/Comparation/eedatacomputePixels.md
    - Conclusion: ./docs/Comparation/conclusion.md

# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist